### PR TITLE
Update projects 20200528

### PR DESCRIPTION
**Pull request by GemCopeland**
Added `end dates` to projects because they were displaying as "ongoing" and cleaned up the URLs. I think in future we should remove "end date" completely, and just display the launch date.

### CODE REVIEW

**Comment by GemCopeland** [comment]
Oh and I added the Labour work too.

**Comment by conatus** [comment]
Thanks @GemCopeland - do you feel that without an image the Labour work feels a bit unbalanced with the rest of it?

**Comment by GemCopeland** [comment]
I don't think so – I originally designed it so it would look ok if we didn't have images for projects. I think having an image of the report cover will feel repetitive as the text will be the same as the project title. Also it's totally reasonable if we do back-end stuff that we wouldn't have a nice image for it.

**Comment by conatus** [comment]
Cool.

**Pull request merged**
