### PR TITLE
Add August and October month notes

### PR DESCRIPTION
**Pull request by Moggach**
## Description
- Adds month notes for August and October to 'writing' section on website

### CODE REVIEW

**Comment by GemCopeland** [comment]
@Moggach hmm, I can't preview it because it says deploy failed. Do you know what's up with it?

**Comment by janbaykara** [comment]
```
3:52:32 PM: error Failed to process image /opt/build/repo/assets/jrf-prototypes-fidelity.png Input file contains unsupported image format
3:52:32 PM:   Error: Input file contains unsupported image format
```

**Comment by janbaykara** [comment]
I think this might just be a random build error... Can we retrigger this with a new commit?

**Comment by Moggach** [comment]
> I think this might just be a random build error... Can we retrigger this with a new commit?

I think it doesn't like the gif - this happened before. I'll replace with a jpeg

**Pull request merged**
