### PR TITLE
Add month notes for June

### PR DESCRIPTION
**Pull request by GemCopeland**

### CODE REVIEW

**Comment by janbaykara** [comment]
LGTM 👍

**Review by janbaykara — APPROVED** [review]
LGTM 👍

**Comment by conatus** [comment]
Gonna make some minor copy edits if I may.

**Comment by chrisdevereux** [comment]
made a couple of quick edits, otherwise looks good

**Review by conatus — APPROVED** [review]
Looks good to me. Made a couple of minor edits and added a boat load more links for fun.

**Pull request merged**
